GO -- GO bloklarý arasý yazýlýmdaki {} gibidir.
DECLARE @sayi tinyint;
SET @sayi=15;
PRINT @sayi;

PRINT GETDATE();


PRINT CONVERT(NVARCHAR(max),@sayi) --@SAYÝ DEÐÝÞKENÝNÝ NVARCHAR A ÇEVÝR.
PRINT CONVERT(NVARCHAR(3),123) -- 123 Ü NVARCHAR A ÇEVÝR.
PRINT RIGHT('mehmet',2) -- SAÐDAKÝ 2 KARAKTERÝ AL.
PRINT REPLICATE('*',5) -- *'I 5 DEFA TEKRAR ET.
PRINT CONVERT(VARCHAR(10),GETDATE(),104) -- 104: DD.MM.YY S:73

PRINT TRY_CONVERT(DATE,'14/02/2009',104)
PRINT TRY_CONVERT(DATE,'10/22/2009') -- ÇEVÝRME BAÞARISIS OLURSA NULL

PRINT CAST('34' AS INT)

-- DATE FONKSÝYONLARI
PRINT DATEDIFF(DD,'05.05.1978',GETDATE()) -- GÜN OLARAK FARK. MM YY
PRINT CAST(DATEPART(DD,'09.09.1990') AS NVARCHAR(MAX)) + '.'+CONVERT(NVARCHAR(MAX),DATEPART(MM,'09.09.1990'))+'.'+ TRY_CONVERT(NVARCHAR(MAX),DATEPART(YYYY,'09.09.1990'))
-- TARÝHÝN PARÇALARINI ALDIK.
PRINT DATENAME(MM,GETDATE()) -- AYIN ADI

PRINT DAY(GETDATE())
PRINT MONTH(GETDATE())
PRINT YEAR(GETDATE())
PRINT @@DATEFIRST --HAFTANIN ÝLK GÜNÜ KAÇINCI GÜNÜ
PRINT EOMONTH(GETDATE()) -- BU AYIN SON GÜNÜ
PRINT CURRENT_TIMESTAMP --Jan  4 2020  9:18AM

--****************************--
PRINT UPPER('mehmet')-- büyüt
PRINT LOWER('MEHMET')-- KÜÇÜLT

PRINT SUBSTRING('Kadýköy',3,5)

PRINT LEN('SÝVASSPOR')

PRINT ROUND(14.7,0) --15
PRINT ROUND(14.2,0) --14 0: VÝRGÜLDEN SONRA KAÇ KARAKTER OLACAK.

PRINT ASCII('V');
PRINT CHAR(86);
PRINT UNICODE('V');

PRINT CHARINDEX('KÖY','KADIKÖY'); --5

PRINT LTRIM('   BJK'); --BJK
PRINT RTRIM('BJK   '); --BJK

SELECT DISTINCT(REPLACE(Country,'USA','Amerika')) Country From Northwind.dbo.Employees
order by Country

PRINT REVERSE('SÝVAS')

PRINT CONCAT('MEHMET ','dEMÝR',99); --BÝRLEÞTÝR

DECLARE @ondalikli FLOAT
SET @ondalikli = 14.9939775;
PRINT STR(@ondalikli,7,2);


DECLARE @durum nvarchar(5);
SET @durum = 'evet';
SELECT CASE @durum WHEN 'evet' THEN 'EEEE' END Durum; -- þart saðlanýyorsa bunu yaz gibi...

DECLARE @ORTALAMAFÝYAT DECIMAL(15,2)
SELECT @ORTALAMAFÝYAT=AVG(UNÝTPRÝCE) FROM PRODUCTS
PRINT 'ORTALAMA BÝRÝM FÝYATI = ' + CAST(@ORTALAMAFÝYAT AS VARCHAR(5))
IF(@ORTALAMAFÝYAT<30)
BEGIN
    PRINT 'DÜÞÜK FÝYAT'
END
ELSE
BEGIN
    PRINT 'YÜKSEK FÝYAT'
END



DECLARE @Sayac TINYINT
SET @Sayac=10
WHILE (@Sayac>0)
BEGIN
    PRINT @Sayac
    SELECT @Sayac=@Sayac-1
END

GO
DECLARE @Sayac INT
SET @Sayac=0
WHILE (@Sayac<10) 
BEGIN 
	SELECT @Sayac=@Sayac+1 
	IF(@Sayac*@Sayac>10)
        BEGIN
            PRINT 'Sayý 10 deðerini geçti.'
            BREAK --döngüden cýk -- CONTINUE
        END
END
GO

DECLARE @kategoriAdi nvarchar(max);
SELECT CategoryName , IIF(CategoryName='Beverages','Ýçecekler','Ýçecek  DIþý') as Türkçe FROM Categories;






PRINT @@MAX_CONNECTIONS 

PRINT @@LANGID

PRINT @@SERVERNAME

PRINT @@SERVICENAME

PRINT @@MICROSOFTVERSION













GO